spring.datasource.url=jdbc:mysql://localhost:3306/ed_tech
spring.datasource.username=root
spring.datasource.password=Sujal4532@

jwt.secret=TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V
jwt.expiration=3000000

cloudinary.cloud-name=rbhrpelm
cloudinary.api-key=325152226364281
cloudinary.api-secret=CHpHQ5__Vzp0XFvS1g-lVxQuZCw
